repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-xml
      - id: debug-statements
      - id: check-added-large-files

  # Add your custom hook below
  - repo: local
    hooks:
      - id: run-unit-tests
        name: Run Unit Tests
        entry: python -m unittest discover
        language: python
        types: [python]
